version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: opkit-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: diasmaksatov
      POSTGRES_PASSWORD: sonit2cx
      POSTGRES_DB: opkit
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
